### ISSUE TITLE
Removing the area (marked part) with the month information

### ISSUE THREAD

**Issue by kksal55** [sud0su/calendar_agenda#1]
How can we remove the marked field? I just want to fetch the field where the dates are.
<img width="486" alt="Ekran Resmi 2021-09-21 11 46 33" src="https://user-images.githubusercontent.com/11652726/134141253-fbacd530-e0ff-4112-90d9-f940fb010fc6.png">

**Comment by sud0su** [comment]
no, for now that's cannot be removed, i think i will add that feature on the next update, thanks for the idea

**Comment by sud0su** [comment]
i am just add updated the package, in the new version you just need to add the options 

```dart
fullCalendar: false
```

**Comment by sud0su** [comment]
I have just updated the package, in the new version you just need to add the options

```dart
fullCalendar: false
```

**Comment by kksal55** [comment]
Thank you @sud0su
