### ISSUE TITLE
Average of selected date

### ISSUE THREAD

**Issue by kksal55** [sud0su/calendar_agenda#2]
It is aligned right or left when the date is selected. Is it possible to add a centering parameter to it?
E.g
<img width="471" alt="Ekran Resmi 2021-09-23 12 40 19" src="https://user-images.githubusercontent.com/11652726/134486283-07a71628-2199-4cc9-917c-5d7ee1f95fad.png">

**Comment by sud0su** [comment]
I'll try to find out how to put the selected date in the center, and I'll update the package

**Comment by sud0su** [comment]
i have updated the package, now you can put the selected day in the center of the day list by adding this option

```dart
        selectedDayPosition: SelectedDayPosition.center,
```

**Comment by kksal55** [comment]
Thank you @sud0su

**Comment by kksal55** [comment]
Thank you @sud0su
